#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "${ROOT}" ]]; then
  echo "Error: run from inside a git repository." >&2
  exit 1
fi
cd "${ROOT}"

if [[ $# -lt 1 ]]; then
  echo "Usage: bash scripts/release/create-tag.sh vX.Y.Z"
  exit 1
fi

TAG="$1"
if [[ ! "${TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "Error: tag must be semantic version style (example: v1.2.3 or v1.2.3-rc.1)." >&2
  exit 1
fi

CURRENT_BRANCH="$(git branch --show-current)"
DEFAULT_BRANCH="$(git symbolic-ref --short refs/remotes/origin/HEAD 2>/dev/null | sed 's#^origin/##' || echo main)"

if [[ "${CURRENT_BRANCH}" != "${DEFAULT_BRANCH}" ]]; then
  echo "Error: create release tags from ${DEFAULT_BRANCH}. Current: ${CURRENT_BRANCH}" >&2
  exit 1
fi

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Error: working tree is not clean. Commit or stash before tagging." >&2
  exit 1
fi

if git rev-parse "${TAG}" >/dev/null 2>&1; then
  echo "Error: tag already exists locally: ${TAG}" >&2
  exit 1
fi

if git ls-remote --tags origin "refs/tags/${TAG}" | grep -q "${TAG}"; then
  echo "Error: tag already exists on origin: ${TAG}" >&2
  exit 1
fi

MESSAGE="Release ${TAG}

Generated by release tag script.
Preflight target:
- npm run release:check"

git tag -a "${TAG}" -m "${MESSAGE}"
git push origin "${TAG}"

echo "Created and pushed tag: ${TAG}"
